### ISSUE TITLE
Add Swift 3 / Xcode 8 support

### ISSUE THREAD

**Issue by Dershowitz011** [uber/rides-ios-sdk#60] opened 2016-07-27 17:01 UTC
When I add `github "https://github.com/uber/rides-ios-sdk" ~> 0.5` , and do a `carthage update`, I get the following error:

```
The following build commands failed:
    Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/Carthage/Checkouts/ObjectMapper/ObjectMapper.xcworkspace -scheme ObjectMapper-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **


The following build commands failed:
    Check dependencies
(1 failure)
** BUILD FAILED **
```

Using `Xcode 8 Beta 3` , macOS `El Capitan 10.11.6`.

**Comment by jbrophy17** [comment] 2016-07-27 18:20
Can you run your carthage command with `--configuration Debug` and post the output here?

To clarify, was this working for you before you started using Xcode 8?

**Comment by Dershowitz011** [comment] 2016-07-27 18:25
I'm sorry I don't understand. What command should I run actually? Yes it worked fine before this.

**Comment by jbrophy17** [comment] 2016-07-27 18:43
`carthage update --platform iOS --configuration Debug`
And then when you run that there should be a line that says `*** xcodebuild output can be found in ` with a file path. Can you include the contents of that file here, it should provide some insight into what went wrong.

**Comment by Dershowitz011** [comment] 2016-07-27 18:52
This is the output I got in `xcodebuild output can be found in /var/folders/d7/4wwjzgsj6qb9g1hdwnzw34v40000gn/T/carthage-xcodebuild.2u26Ow.log` :

```
/usr/bin/xcrun xcodebuild -workspace /Users/Carthage/Checkouts/ObjectMapper/ObjectMapper.xcworkspace -scheme ObjectMapper-iOS -configuration Debug -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean buildBuild settings from command line:
    BITCODE_GENERATION_MODE = bitcode
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos10.0

=== CLEAN TARGET ObjectMapper-iOS OF PROJECT ObjectMapper WITH CONFIGURATION Debug ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

=== BUILD TARGET ObjectMapper-iOS OF PROJECT ObjectMapper WITH CONFIGURATION Debug ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.


```

**Comment by jbrophy17** [comment] 2016-07-27 19:35
Okay so looks like the problem is that by default Xcode 8 is using Swift 3, but the dependencies are using Swift 2. I think you should be able to get around this by using this command:
```
TOOLCHAINS=com.apple.dt.toolchain.Swift_2_3 carthage update --platform iOS
```

**Comment by Dershowitz011** [comment] 2016-07-28 12:40
Same error but it's like this now:

```
The following build commands failed:
	CompileSwift normal arm64 /Users/shantanudesai/Desktop/App dev/Touch-ID/Carthage/Checkouts/rides-ios-sdk/source/UberRides/Utilities/RidesUtil.swift
	CompileSwift normal arm64 /Users/shantanudesai/Desktop/App dev/Touch-ID/Carthage/Checkouts/rides-ios-sdk/source/UberRides/RideRequestView.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
```

**Comment by jbrophy17** [comment] 2016-07-28 16:32
Can you provide the xcode build output for that command as well? I think fixing this for xcode 8 might require some updates to the project to specify what version of Swift to use

**Comment by Dershowitz011** [comment] 2016-07-28 16:42
Is this what you mean:

```
/usr/bin/xcrun xcodebuild -workspace /Users/Desktop/Carthage/Checkouts/ObjectMapper/ObjectMapper.xcworkspace -scheme ObjectMapper-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean buildBuild settings from command line:
    BITCODE_GENERATION_MODE = bitcode
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos10.0
    TOOLCHAINS = com.apple.dt.toolchain.Swift_2_3
```

**Comment by jbrophy17** [comment] 2016-07-28 20:58
No, I mean the build log like you included before. I will need to investigate more into Issues caused from Xcode 8 / Swift 3

**Comment by Dershowitz011** [comment] 2016-07-29 13:23
It's more than a 1000 lines. For every file included in the SDK, there's an error. 
[carthage.txt](https://github.com/uber/rides-ios-sdk/files/390577/carthage.txt)

**Comment by Dershowitz011** [comment] 2016-07-31 03:17
Do help. No matter what I do, it just isn't getting integrated. Tried a lot. But in vain. :(

**Comment by jbrophy17** [comment] 2016-07-31 04:34
Sorry, I haven't had a chance to investigate these issues with the Xcode 8 beta yet. Can you share what you've tried so far so I don't duplicate your efforts?

**Comment by Dershowitz011** [comment] 2016-07-31 04:41
When I do `carthage update --platform iOS --configuration Debug`, I get:

```
/usr/bin/xcrun xcodebuild -workspace /Users/shantanudesai/Desktop/App dev/TestApp/Carthage/Checkouts/ObjectMapper/ObjectMapper.xcworkspace -scheme ObjectMapper-iOS -configuration Debug -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean buildBuild settings from command line:
    BITCODE_GENERATION_MODE = bitcode
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos10.0

=== CLEAN TARGET ObjectMapper-iOS OF PROJECT ObjectMapper WITH CONFIGURATION Debug ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

=== BUILD TARGET ObjectMapper-iOS OF PROJECT ObjectMapper WITH CONFIGURATION Debug ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
```

**Comment by Dershowitz011** [comment] 2016-07-31 05:07
I think the problem is with `TOOLCHAIN` part where I don't have toolchains at all. I only have `Xcode 8 Beta 3` AND `Xcode 7.3.1`. Is this of any relevance @jbrophy17 ?

**Comment by jbrophy17** [comment] 2016-08-01 21:15
Okay so it looks like it is definitely an issue with the newest version of Swift, which the SDK has not been updated for yet. Is your project currently using Swift 3 features? If not, you might be able to get things to work by setting the *Use Legacy Swift Language Version* in your project's build settings to Swift 2.3 for now.

**Comment by Dershowitz011** [comment] 2016-08-01 21:19
Yes my project is using the swift 3 @jbrophy17 :( . I tried every possible workaround. Nothing works. The whole SDK has to be written in swift 3 now. What do we do? Any suggestions? Please?

**Comment by jbrophy17** [comment] 2016-08-02 18:47
Due to the incompatibility between swift 2 and 3 we are going to need to make a separate Swift 3 branch. Unfortunately, because of staffing, we likely won't have that ready for a few weeks. However, if you want to take a swing at it and submit a PR, we would be happy to work with you on it

**Comment by dayitv89** [comment] 2016-09-14 20:35
@jbrophy17 Does 0.6.x supports for Swift 3.0? Or Any other branch you take for swift 3.0 contributions.

**Comment by instadealApp** [comment] 2016-09-15 17:56
any news on the swift3 branch?

**Comment by jbrophy17** [comment] 2016-09-15 18:29
I'm in the process of putting up dev branches for swift 2.3 & swift 3. However, for now, they are just for contributors who want to help with the migration, they are not production ready yet.

**Comment by jbrophy17** [comment] 2016-09-15 18:55
added branches swift-2.3-dev and swift-3-dev

swift-2.3-dev has gone through the migrator to update syntax to 2.3, but some tests are still failing around the keychain & saving tokens

swfit-3-dev has not gone through the migrator yet, I made an initial pass but there were just too many errors for me to address before pushing it up. I updated the cartfile to use the swift-3 branches for the dependencies, however

**Comment by karthikasdas** [comment] 2016-09-17 09:05
Hi,
I am using cocoa pods for Uber SDK. It shows lots of errors when upgraded to Xcode 8. When can we expect new uber sdk that is swift 3 compatible?

**Comment by jbrophy17** [comment] 2016-09-20 01:53
Adding Swift 3 support is on our roadmap, but we don't have an exact timeline of when it will be complete yet. In the meantime, we have a swift-3-dev branch where we are happy to review & merge PRs towards Swift 3 compatibility

**Comment by butterpuf** [comment] 2016-09-30 06:31
Hi

I have tried pod 'ObjectMapper', '~> 2.0' in my project with xcode 8.0
I did not work. 
Any Help?

Regards

**Comment by brandify-justin** [comment] 2016-10-20 21:28
Hello. I am just curious if there are any updates on this?

**Comment by jpsanabria** [comment] 2016-10-23 06:35
Any updates on the Swift 3 usability of the Uber Rides SDK. I'm using Cocoapods

**Comment by jbrophy17** [comment] 2016-10-25 08:44
Hi guys, sorry about the delay here. We still don't have a timeline of when Swift 3 support will be added, but understand that it is a pressing issue. Currently, #111 looks promising for adding support, but there are a few comments to be addressed still

**Comment by hardik2810** [comment] 2016-11-07 13:17
Hi. The latest SDK doesn't seem to be Swift 2.3 compatible either. Is there an ETA on that? It'll really help to know when we might expect an updated SDK with 2.3 and xcode 8 support out of the box.

FYI, Regarding swift 2.3 update, looks like there are only a couple of issues 
1. RidesUtil.swift | line #73 
2. RideRequestView.swift | line #219  

Please do let us know.

**Comment by jbrophy17** [comment] 2016-11-08 02:08
Hey all, wanted to give a quick update on this. The current plan is to do a final 2.2 release with a whole bunch of bug fixes and then follow that up with an update to 2.3. I am hoping to get the 2.2 updates out this week, and the 2.3 should follow soon after that

**Comment by danielmhanover** [comment] 2016-11-15 23:22
What is the status on Swift 3 support? The pesky ObjectMapper 1.0 dependency still seems to be causing problems.

**Comment by jbrophy17** [comment] 2016-11-19 01:12
Just released the final Swift 2.2 supported version, now starting work to get Swift 2.3 support. Swift 3 will be coming after that, but unfortunately I don't have a solid timeline at this point

**Comment by jbrophy17** [comment] 2016-12-29 16:54
Hello Everyone,
We understand that this is an inconvenience and want to ensure you that we have not forgotten about it.

The language changes for Swift 3 change many internal APIs, but also introduce a whole new set of API design guidelines. Before we release an updated SDK, we want to make sure that our APIs are updated to meet these guidelines, in order to minimizing the friction of upgrading & working with the SDK in the future.

I have just opened a few issues to track what needs to be completed for the Swift 3 updates of the SDK. (#149, #150, #151, #152, #153). We are targeting the second half of January for this work. However, in the meantime, if anybody in the community wants to start working on these issues, we are happy to review PRs. I would suggest making them against the `swift-3-dev` branch & continuing to use this issue as a place to discuss changes.

Again, we apologize for the inconvenience and thank you for your understanding.

**Comment by scottrhoyt** [comment] 2017-01-06 06:25
It might be valuable to just release a working Swift 3 version before working towards meeting the API guidelines. Seeing as this is pre-1.0 you can then focus on the API guidelines even if it means another breaking change. As this probably isn't a dependency to many other popular libraries, version pinning is a viable option for most of us downstream.

**Comment by ganeshcssun** [comment] 2017-01-06 12:36
I need the working Uber Rides to integrate in my application when can i expect the SDK to be ready
OR
Is there any other way so that I can integrate the SDK in swift 3

**Comment by Sml995** [comment] 2017-01-26 12:30
Hi ! Maybe you have some news about the swift 3 integration?

**Comment by jbrophy17** [comment] 2017-01-27 00:26
Hey all,
Just wanted to let you know that I am actively working on this and you should expect a working Swift 3 version soon. I will be pushing a version up to the `swift-3-dev` branch that will close #149

**Comment by erusso1** [comment] 2017-02-02 23:40
Hey what's the status of this? As of right now, the swift-3-dev version still has a dependency on ObjectMapper 1.0, which isn't using swift 3. I believe they have 2.2.2 now using swift 3.

**Comment by jbrophy17** [comment] 2017-02-04 03:48
Hey all,
I have just pushed up a Swift 3 compatible version to the `swift-3-dev branch`. It hasn't made any of the changes for the new API design guidelines, but will compile and work for your Swift 3 projects. I will continue to update this thread as we continue to work on full Swift 3 support

Carthage:
update your cartfile to contain
```
github "https://github.com/uber/rides-ios-sdk.git" "swift-3-dev"
```

Cocoapods:
update your podfile to contain:
```
pod "UberRides", :git => "https://github.com/uber/rides-ios-sdk.git", :branch => "swift-3-dev"
```

**Comment by Festyk** [comment] 2017-02-06 11:08
Thank you. I can confirm that it's works.

**Comment by rejdic** [comment] 2017-02-23 17:01
Hey guys, any updates on this?

**Comment by rejdic** [comment] 2017-02-23 17:02
Hey guys, any updates on this?

**Comment by rejdic** [comment] 2017-02-23 17:04
Hey guys, any updates on this?

**Comment by mikerojaswa** [comment] 2017-03-11 03:26
Also can confirm this works!

**Comment by varunbabu008** [comment] 2017-05-20 16:35
It works for now.

**Comment by ezanalemma** [comment] 2017-07-05 00:44
Why is it still not working for me on Swift 3?

**Comment by edjiang** [comment] 2017-07-06 21:28
@ezanalemma this should work on Swift 3! Please read the note on #167 for more details.

Closing this in favor of #167

**Closed by edjiang** 2017-07-06 21:28 UTC

**Comment by ThulaniMtetwa** [comment] 2018-10-20 04:04
I am using Xcode 10.0. The pod "UberRides", :git => "https://github.com/uber/rides-ios-sdk.git", :branch => "swift-3-dev" solution still require a migration. What is the fix for this ?

**Comment by edjiang** [comment] 2018-10-22 23:39
v0.11.0 will work for you :)
