### ISSUE TITLE
Add delegate for success of ModalRideRequestViewController for ride requests

### ISSUE THREAD

**Issue by noonhub** [uber/rides-ios-sdk#54] opened 2016-07-07 23:51 UTC
In addition to having the delegate inside of `ModalRideRequestViewController` called for errors, it would be helpful for successful ride requests to call the delegate in order to easy implement custom logic around when a ride request returns a success response.

**Comment by jbrophy17** [comment] 2016-07-08 00:08
@noonhub by 'success' do you mean initiating a request or completing a ride? Or somewhere in-between?

**Comment by noonhub** [comment] 2016-07-08 01:01
I think that all trip states would be useful

On Thu, Jul 7, 2016 at 5:09 PM, John Brophy <notifications@github.com>
wrote:

> @noonhub <https://github.com/noonhub> by 'success' do you mean initiating
> a request or completing a ride? Or somewhere in-between?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/uber/rides-ios-sdk/issues/54#issuecomment-231243094>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA5hGzDcspd_Gbek7zh1-D_rnPy6xYLTks5qTZVAgaJpZM4JHm7C>
> .
>



-- 
Andrew Noonan
Partner Engineer, Developer Platform
215.292.5083  |  noonan@uber.com  |  @noonisms
<https://www.twitter.com/noonisms>

**Comment by jbrophy17** [comment] 2016-07-08 01:03
I agree, going to close this as a duplicate of #53

**Closed by jbrophy17** 2016-07-08 01:03 UTC
Labels: enhancement
