### ISSUE TITLE
Cannot  Cheapest Product

### ISSUE THREAD

**Issue by nlhdung** [uber/rides-ios-sdk#164] opened 2017-05-31 04:10 UTC
I'm using  your uber SDK on iOS app. Last days, I can get cheapest product with ridesClient.fetchCheapestProduct() function. But today, that function always return nil value. 
Any problem with your server or sdk. Please help me about this issue
(I'm in Vietnam and my client_id still works fine for Android)
Thanks

**Comment by edjiang** [comment] 2017-07-10 23:13
Hey @nlhdung, I'm unable to reproduce this bug. Can you please give me more details about how you're using the SDK? 

Are you getting an error in the response object? If so, are you adding your Server Token properly?

See here: https://github.com/uber/rides-ios-sdk#sdk-configuration

**Comment by edjiang** [comment] 2017-07-10 23:14
Since this is question is from over a month ago, I'm going to close this until further response :)

**Closed by edjiang** 2017-07-10 23:14 UTC
