### ISSUE TITLE
Drop-off location not shown in Uber app

### ISSUE THREAD

**Issue by ir-fuel** [uber/rides-ios-sdk#166] opened 2017-06-12 15:02 UTC
This is the code in my Swift iOS app
```
        let dropoffLocation = CLLocation(latitude: reservation.coordinate.latitude, longitude: reservation.coordinate.longitude)
        let builder = RideParametersBuilder().setDropoffLocation(dropoffLocation,nickname: reservation.restaurantName)
        uberButton.rideParameters = builder.build()
```

When I push the Uber button the Uber app opens, but it does not show a destination, it just asks me "Where to?"

What am I doing wrong?

Thanks!

**Comment by edjiang** [comment] 2017-07-10 23:33
Hey @ir-fuel, I'm not able to reproduce this. Are you using the latest Uber app? 

If not, can you please let me know how you're using the SDK? 

Closing, since this issue was opened a month ago. When you reply, I'll re-open this GH issue :)

**Closed by edjiang** 2017-07-10 23:33 UTC
