### ISSUE TITLE
UberRide-Swift.h header not generated in Swift 3

### ISSUE THREAD

**Issue by saintjab** [uber/rides-ios-sdk#120] opened 2016-09-29 23:00 UTC
Prior to Xcode 8 which shipped off with Swift 3.0, Xcode 7.3.1 was auto-generating UberRide-Swift.h header when the UberRide SDK is used in an Objective-c project so the SDK can be used but this is no longer happening in the new Xcode 8.0. Help

**Comment by jbrophy17** [comment] 2016-09-30 18:11
Thanks for opening this issue, we are currently in the process of porting the SDK to swift 3, and will be sure to get the Obj-c compatibility working. 

Could you provide the exact error that you are seeing?

**Comment by saintjab** [comment] 2016-10-01 10:36
It 'UberRide-Swift.h' file not found. I think it has to do with the SDK not generating the required header for bridging swift with objective-c.

**Comment by edjiang** [comment] 2017-07-11 00:48
Closing since this issue is from before the Swift 3 release, and not reproducible anymore.

**Closed by edjiang** 2017-07-11 00:48 UTC
