### ISSUE TITLE
User cancelled the login - Swift 3 bug

### ISSUE THREAD

**Issue by Avinodh** [uber/rides-ios-sdk#162] opened 2017-04-26 22:07 UTC
Hi! I'm facing the following issue: After clicking the Uber Login Button in my app, I get redirected to the native Uber app where I click "Allow". However, I see the following error in the console once I am redirected back to my app:
Error Domain=com.uber.rides-ios-sdk.ridesAuthenticationError Code=25 "User cancelled the login process." UserInfo={NSLocalizedDescription=User cancelled the login process.}

Using Swift 3. Would appreciate any help!

**Comment by avianydo** [comment] 2017-06-01 09:15
This happens to me also.

**Comment by edjiang** [comment] 2017-07-06 22:01
Duplicate of #90. I'll be looking into this as part of enhancements to the SDK. However, I don't anticipate that we will update the Swift 2.3 version with any fixes.

**Closed by edjiang** 2017-07-06 22:01 UTC
Labels: bug
